apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default project for application deployments
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Admin role with full access
      policies:
        - p, proj:default:admin, applications, *, default/*, allow
        - p, proj:default:admin, repositories, *, default/*, allow
      groups:
        - admin
    - name: developer
      description: Developer role with limited access
      policies:
        - p, proj:default:developer, applications, get, default/*, allow
        - p, proj:default:developer, applications, sync, default/*, allow
      groups:
        - developers
