apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-project
  namespace: argocd
  labels:
    app.kubernetes.io/name: app-project
    app.kubernetes.io/part-of: argocd
spec:
  description: Application project for CI/CD pipeline
  sourceRepos:
    - '*'
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Admin role with full access
      policies:
        - p, proj:app-project:admin, applications, *, app-project/*, allow
        - p, proj:app-project:admin, repositories, get, app-project/*, allow
        - p, proj:app-project:admin, repositories, create, app-project/*, allow
        - p, proj:app-project:admin, repositories, update, app-project/*, allow
        - p, proj:app-project:admin, repositories, delete, app-project/*, allow
      groups:
        - admin
    - name: developer
      description: Developer role with limited access
      policies:
        - p, proj:app-project:developer, applications, get, app-project/*, allow
        - p, proj:app-project:developer, applications, sync, app-project/*, allow
      groups:
        - developers
  syncWindows:
    - kind: allow
      schedule: '* * * * *'
      duration: 24h
      applications:
        - '*'
    - kind: deny
      schedule: '0 2 * * *'
      duration: 1h
      applications:
        - '*-prod'
      manualSync: true
